### ISSUE TITLE
branch name in the PR comment

### ISSUE THREAD

**Issue by sophiaaar** [exercism/pr-commenter-action#8]
use case: i want to use the PR commenter action to leave a comment on a PR with a link that changes depending on the base branch name.

I had a look at using environment variables, but I couldn't get it to work, so i thought i'd try creating an issue just in case theres something that can be implemented in the config file or something :) like a kind of pseudo env var potentially

**Comment by angelikatyborska** [comment]
Hi! Thank you for the issue. As far as I know, there is no way to achieve this with the current version of the action.

I can definitely see how that could be useful.

One option of implementing this would be to allow the comment to be a some sort of template, e.g. a mustache template, like the Labeler Commenter action offers (their implementation: https://github.com/peaceiris/actions-label-commenter/blob/main/src/main.ts#L159-L187). I would need to choose a set of values that make sense that could be used in the comment snippet. This would mean that you could use the branch name to compose the URL, but it might be difficult to transform it in any way (e.g. URL encode) or do any conditionals with it (`if branch_name == "main"`). Mustache doesn't even have conditionals.

Another option that I have been considering for my own use case is to allow defining a path to a script instead of a comment snippet body. The script would be responsible for returning a success status code if a comment snippet should be included in the comment and printing a string that would be used as the comment snippet body. The script would have access to all the files in the repository, but it could also use Oktokit to get information about the PR, like the branch name, author GitHub handle etc.

The latter would allow me to add comment snippets like "Don't forget to add your GitHub handle to this file" but I could first check if that's actually needed - maybe they already did.

What do you think? What would be your preferred way of achieving what you need?

**Comment by sophiaaar** [comment]
hi, thanks for replying!

i think an ideal solution for me personally would be to have some way to define a variable or something in the workflow file that i could then use in the config file, but im really happy with anything! perhaps the defining a path to a script solution would be the most flexible though.

**Comment by angelikatyborska** [comment]
I scraped that complex proposal and went with a simple solution. @sophiaaar if you have a spare minute, can you take a look at https://github.com/exercism/pr-commenter-action/pull/12 ? I think that should fulfill your needs

**Comment by angelikatyborska** [comment]
Release 1.2.0 published
